-- +goose Up
-- +goose StatementBegin
CREATE TABLE trips
(
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trip_id     uuid  NOT NULL,
    offer_id    varchar  NOT NULL,
    from_offer        jsonb NOT NULL,
    to_offer         jsonb NOT NULL,
    price       jsonb NOT NULL,
    trip_status varchar NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- +goose StatementEnd
